services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ..:/workspaces/spring-postgres
    ports:
      - "8080:8080"
    command: sleep infinity
    networks:
      - my_network

  database:
    container_name: postgresdb
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data: