parameters:
  - name: poolVmImage
    type: string
    default: "ubuntu-22.04"
  - name: poolName
    type: string
    default: ""
  - name: environments
    type: object
  - name: azureSubscriptionTemplate
    type: string
    default: ""
  - name: acrNameTemplate
    type: string
    default: ""
  - name: imagePathPrefix
    type: string
    default: ""
  - name: gitopsPromotionTag
    type: string
    default: "v1.3.1"
  - name: awsServiceConnectionTemplate
    type: string
    default: ""
  - name: awsRegion
    type: string
    default: ""
  - name: group
    type: string
    default: ""
  - name: cloud
    type: string
    default: "azure"

stages:
  - stage: push
    jobs:
      - ${{ each env in parameters.environments }}:
          - template: push.yaml
            parameters:
              poolVmImage: ${{ parameters.poolVmImage }}
              poolName: ${{ parameters.poolName }}
              environment: ${{ env.name }}
              awsServiceConnection: ${{ format(parameters.awsServiceConnectionTemplate, env.name) }}
              azureSubscription: ${{ format(parameters.azureSubscriptionTemplate, env.name) }}
              acrName: ${{ format(parameters.acrNameTemplate, env.name) }}
              imagePathPrefix: ${{ parameters.imagePathPrefix }}
              awsRegion: ${{ parameters.awsRegion }}
              cloud: ${{ parameters.cloud }}

  - stage: feature
    dependsOn: [push]
    jobs:
      - template: feature.yaml
        parameters:
          poolVmImage: ${{ parameters.poolVmImage }}
          poolName: ${{ parameters.poolName }}
          gitopsPromotionTag: ${{ parameters.gitopsPromotionTag }}
          group: ${{ parameters.group }}
