apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps-qa
spec:
  interval: "1m"
  timeout: "30s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: tenant
  path: "./apps/qa"
  serviceAccountName: "flux"
