parameters:
  - name: poolNameTemplate
    type: string
    default: ""
  - name: poolVmImage
    type: string
    default: "ubuntu-22.04"
  - name: azureSubscriptionTemplate
    type: string
  - name: resourceGroupTemplate
    type: string
  - name: packerTemplateRepo
    type: string
    default: "https://github.com/XenitAB/cloud-automation.git"
  - name: packerTemplateRepoBranch
    type: string
    default: "master"
  - name: packerTemplateFile
    type: string
    default: ""
  - name: preBuild
    type: stepList
    default: []
  - name: postBuild
    type: stepList
    default: []
  - name: binaries
    type: object
    default:
      packer:
        tag: "1.6.5"
        sha: "a49f6408a50c220fe3f1a6192ea21134e2e8f31092c507614cd27ad4f913234b"
  - name: environments
    type: object
    default:
      - name: prod

stages:
  - stage: build
    jobs:
      - ${{ each env in parameters.environments }}:
          - template: build_image.yaml
            parameters:
              poolNameTemplate: ${{ parameters.poolNameTemplate }}
              poolVmImage: ${{ parameters.poolVmImage }}
              environment: ${{ env.name }}
              azureSubscription: ${{ format(parameters.azureSubscriptionTemplate, env.name) }}
              resourceGroup: ${{ format(parameters.resourceGroupTemplate, env.name) }}
              packerTemplateRepo: ${{ parameters.packerTemplateRepo }}
              packerTemplateRepoBranch: ${{ parameters.packerTemplateRepoBranch }}
              packerTemplateFile: ${{ parameters.packerTemplateFile }}
              preBuild: ${{ parameters.preBuild }}
              postBuild: ${{ parameters.postBuild }}
              binaries: ${{ parameters.binaries }}
